export default {
  CDN: 'https://cdn.bootcdn.net/ajax/libs/prism-themes/1.9.0', // 代码样式文件cdn
  CODE_THEME: [
    'a11y-dark',
    'atom-dark',
    'base16-ateliersulphurpool.light',
    'cb',
    'coldark-cold',
    'coldark-dark',
    'coy-without-shadows',
    'darcula',
    'dracula',
    'duotone-dark',
    'duotone-earth',
    'duotone-forest',
    'duotone-light',
    'duotone-sea',
    'duotone-space',
    'ghcolors',
    'gruvbox-dark',
    'gruvbox-light',
    'holi-theme',
    'hopscotch',
    'lucario',
    'material-dark',
    'material-light',
    'material-oceanic',
    'night-owl',
    'nord',
    'one-dark',
    'one-light',
    'pojoaque',
    'shades-of-purple',
    'solarized-dark-atom',
    'synthwave84',
    'vs',
    'vsc-dark-plus',
    'xonokai',
    'z-touch',
  ],
  CONTENT_THEME: [
    {
      value: 'Chinese-red',
      label: 'Chinese-red',
    },
    {
      value: 'awesome-green',
      label: 'awesome-green',
    },
  ],
  CONTENT_THEME_PATH: '/api/editor/theme',
};
